services:
  web:
    image: nginx:1.26.0-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-web
    ports:
      - "80:80"
    volumes:
      - ./back/app/public:/app/public:ro
      - ./back/docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal-network
  php:
    build:
      context: back
      target: app_php_dev
      args:
        APP_UID: ${UID:-1000}
        APP_GID: ${GID:-1000}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    volumes:
      - ./back/app:/app
    environment:
      XDEBUG_MODE: develop
      XDEBUG_SESSION: phpstorm
      SYMFONY_VERSION: ${SYMFONY_VERSION-stable}
    networks:
      - internal-network
  database:
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_USER: "championship"
      POSTGRES_DB: "championship"
      POSTGRES_PASSWORD: "p@ssw0rd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/database:/var/lib/postgresql/data
    networks:
      - internal-network
  frontend:
    build:
      context: front
    ports:
      - 3000:3000
    volumes:
      - ./front/code:/code
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME}-network
